version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: catalog-service/Catalog.API/Dockerfile
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: basket-service/API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: discount-service/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: discount-service/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: ordering-service/Ordering.API/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  




