version: '3.4'

services:
  catalogdb:
    image: mongo
  basketdb:
    image: redis
  discountdb:
    image: postgres
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: catalog-service/Catalog.API/Dockerfile
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: basket-service/API/Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: discount-service/Discount.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: discount-service/Discount.Grpc/Dockerfile

volumes:
  mongo_data:
  postgres_data:
  



