version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  discountdb:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=123456789
    - POSTGRES_DB=discount
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    depends_on: 
      - catalogdb
    ports:
      - "5153:80"

  api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:Redis=basketdb:6379
      - GrpcSettings:DiscountUrl=http://discount.grpc
    depends_on:
      - basketdb
      - discount.grpc
    ports:
      - "5169:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:Pgsql=Server=discountdb;Port=5432;Database=discount;User Id=admin;Password=123456789
    ports:
      - "5145:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings:Pgsql=Server=discountdb;Port=5432;Database=discount;User Id=admin;Password=123456789
    ports:
      - "5181:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
